### ISSUE TITLE
[I/O Site] incorrect 404 page rendering on newrelic.com/instant-observability

### ISSUE THREAD

**Issue by jpvajda** [newrelic/instant-observability-website#99]
The [gatsby-theme 404](https://developer.newrelic.com/404) don't seem to actually be rendering  when a user hits a 404 page on [newrelic.com/instant-observability](https://newrelic.com/instant-observability/4040404).

**Comment by nr-kkenney** [comment]
i started by investigating the broken 404 page since we want to make sure that page works correctly before we purposefully redirect to it.

if we visit a page that does not exist on our site, [for example](https://instantobservabilitywebsite.gatsbyjs.io/instant-observability/codestreams/29bd9a4a-1c19-4219-9694-0942f6411ce7), if we look at the console logs we will see:

```none
react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'load')
    at tessen.js:76:21
    at H (tessen.js:38:10)
    at Module.z (on-route-update.js:5:3)
    at api-runner-browser.js:26:34
    at Array.map (<anonymous>)
    at n.h (api-runner-browser.js:17:25)
    at S (navigation.js:44:5)
    at n.a.componentDidMount (navigation.js:224:5)
    at gu (react-dom.production.min.js:219:411)
    at Mi (react-dom.production.min.js:259:160)
```

so it looks like failing to load tessen is the reason for the broken page. if we look at the network tab, we see:
```
Request URL: https://instantobservabilitywebsite.gatsbyjs.io/tessen.min-1.14.0.js
Request Method: GET
Status Code: 404
```
for the call which tries to get tessen. it turns out, by adding a path prefix for our site, that resource now lives at `https://instantobservabilitywebsite.gatsbyjs.io/instant-observability/tessen.min-1.14.0.js`.

as my next step, I tried to think about what we could do. it seems like we could:
1. move the resource to the right spot (root of the domain) while still using path prefix.
2. remove path prefix.
3. create a new / shadowed 404 page to look at the correct spot for tessen or not break when tessen isn't there.
4. update the theme so we can supply a path for where to look, or something similar (modify the 404 page, etc).

i don't think we can do option 1, and i dont think we want to do option 4. i have a solution already in place for option 3 which can be seen [here](https://instantobservabilitywebsite404.gatsbyjs.io/codestreams/29bd9a4a-1c19-4219-9694-0942f6411ce7) for example. however, option 3 feels kind of cludgey & awkward, since we are adding code to handle this particular feature of gatsby that we're using.

my opinion: i think we should do option 2 since all it requires is removing one line of code for a feature that I don't think we need.

**Comment by nr-kkenney** [comment]
ive reached out to the website team and seo folks. moving this to blocked until we get some feedback from them and @aswanson-nr

**Comment by nr-kkenney** [comment]
update: met with erik on the website team. he is out this week, but when he is back he will need to do some research into the best way to proceed for what we want (and how to do it). 

this ticket will likely be blocked for a while. we can split this ticket out into two pieces:
* fix the broken 404 page
* have the main site use our 404 page

then we can work on the first piece, while the second piece remains blocked.

**Comment by aswanson-nr** [comment]
Hey @nr-kkenney, thanks for this fantastic write up. 
My main question is, why does a 404 for tessen cause the page to break? It's an analytics script and should not affect the execution of javascript within a page. This could have downstream effects if an adblocker stops tessen from loading.

Ignoring the question above, option 3 does seem like the easiest solution in the short run, but would require keeping it in sync with the theme. Overall, option 4 seems like the correct solution. Our theme should support path prefixes since Gatsby supports them. That field is available in the `gatsby-config.js`, so it should be possible to pull that in and prefix the tessen call in the theme.

**Comment by nr-kkenney** [comment]
here is the nice error UI from gatsby when running in develop mode:
![Screen Shot 2022-04-04 at 10 41 10 AM](https://user-images.githubusercontent.com/70179215/161600862-98d0a1da-fb9b-4a44-a805-7164614f1d00.png)

**Comment by nr-kkenney** [comment]
with the PRs above merged, 404 page is now working for the site: [example](https://instantobservabilitywebsite.gatsbyjs.io/instant-observability/apple/banana).

whats left for this ticket is getting our custom 404 page to show. that will require research from the website team.

**Comment by zstix** [comment]
The remaining work for this is going to get picked up after FutureStack deliverables have been completed.

I've created a JIRA issue to ensure we keep track of this while moving where we track our work. I'll make sure both are updated, since this is in flight.
